// src/angular/src/app/app.component.ts
import { AfterViewInit, Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  imports: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements AfterViewInit {
  title = 'angular';

  @ViewChild('modal', { static: false }) modal!: ElementRef;

  ngAfterViewInit() {
    // Logs the modal's `open` property
    console.log(this.modal.nativeElement.open);
  }

  openModal() {
    if (this.modal) {
      // Check modal state
      console.log(this.modal.nativeElement.open);
      // Call the `show()` method
      this.modal.nativeElement.show();
    }
  }
}

<main class="main">
  <h1>DÁP DS example</h1>
  <div>
    <dap-ds-button (click)="openModal()">Open</dap-ds-button>
    <dap-ds-modal
      #modal
      title="This is a title"
      description="Description of the modal">
    </dap-ds-modal>
  </div>
  <div>
    <dap-ds-badge>Default Badge</dap-ds-badge>
  </div>
  <div>
    <dap-ds-banner>You have a new package!</dap-ds-banner>
  </div>
  <div>
    <dap-ds-accordion-group>
      <dap-ds-accordion>
          <span slot="heading">First accordion</span>
          <dap-ds-typography variant="body" size="md">
            Firrrst Nam ultricies justo magna, id scelerisque mauris tempus
            non. Curabitur viverra nulla leo, a rutrum nisi porta a. Duis tempor
            enim lorem, vestibulum facilisis tortor pharetra quis.
          </dap-ds-typography>
      </dap-ds-accordion>
      <dap-ds-accordion>
        <span slot="heading">Second accordion</span>
        <dap-ds-typography variant="body" size="md">
          Second Nam ultricies justo magna, id scelerisque mauris tempus
          non. Curabitur viverra nulla leo, a rutrum nisi porta a. Duis tempor
          enim lorem, vestibulum facilisis tortor pharetra quis.
        </dap-ds-typography>
      </dap-ds-accordion>
   </dap-ds-accordion-group>
  </div>
</main>

// src/react/src/App.tsx
import { useState } from 'react';
import './App.css'
import { DapDSModalReact, DapDSButtonReact, DapDSBadgeReact, DapDSBannerReact, DapDSAccordionGroupReact, DapDSAccordionReact, DapDSTypographyReact } from 'dap-design-system/dist/react'

function App() {
  const [opened, setOpened] = useState(false);

  const openModal = () => {
    setOpened(true);
  }

  const closeModal = () => {
    setOpened(false);
  }

  return (
    <>
      <main className="main">
        <h1>DÁP DS example</h1>
        <div>
          <DapDSButtonReact onClick={openModal}>Open</DapDSButtonReact>
          <DapDSModalReact
            open={opened}
            onDdsClose={closeModal}
            title="This is a title"
            description="Description of the modal">
          </DapDSModalReact>
        </div>
        <div>
          <DapDSBadgeReact>Default Badge</DapDSBadgeReact>
        </div>
        <div>
          <DapDSBannerReact>You have a new package!</DapDSBannerReact>
        </div>
        <div>
          <DapDSAccordionGroupReact>
            <DapDSAccordionReact>
                <span slot="heading">First accordion</span>
                <DapDSTypographyReact variant="body" size="md">
                  Firrrst Nam ultricies justo magna, id scelerisque mauris tempus
                  non. Curabitur viverra nulla leo, a rutrum nisi porta a. Duis tempor
                  enim lorem, vestibulum facilisis tortor pharetra quis.
                </DapDSTypographyReact>
            </DapDSAccordionReact>
            <DapDSAccordionReact>
              <span slot="heading">Second accordion</span>
              <DapDSTypographyReact variant="body" size="md">
                Second Nam ultricies justo magna, id scelerisque mauris tempus
                non. Curabitur viverra nulla leo, a rutrum nisi porta a. Duis tempor
                enim lorem, vestibulum facilisis tortor pharetra quis.
              </DapDSTypographyReact>
            </DapDSAccordionReact>
          </DapDSAccordionGroupReact>
        </div>
      </main>
    </>
  )
}

export default App
